# Generated by Django 3.2.23 on 2024-03-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
