# Generated by Django 3.2.23 on 2024-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0009_alter_normaluser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='upload/', verbose_name='晒图')),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
