# Generated by Django 3.2.23 on 2024-04-03 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0010_takeimage'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='food',
        #     name='newCode',
        #     field=models.CharField(default='', max_length=50, null=True, verbose_name='商品唯一编码'),
        # ),
        migrations.AddField(
            model_name='food',
            name='newSpec',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='newStatus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='newUnit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat', to='ServerApp.goodscategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServerApp.goodscategory', verbose_name='商品类目'),
        ),
    ]
