# Generated by Django 3.2.23 on 2024-05-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0011_auto_20240403_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True, verbose_name='是否可定')),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='time',
            new_name='add_time',
        ),
        migrations.AddField(
            model_name='food',
            name='newCode',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='商品唯一编码'),
        ),
    ]
