# Generated by Django 3.2.23 on 2024-06-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0013_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
