# Generated by Django 3.2.23 on 2024-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0014_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='telephone',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=models.URLField(default='', max_length=100),
        ),
    ]
