# Generated by Django 3.2.23 on 2024-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0015_auto_20240620_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.TextField(null=True),
        ),
    ]
