# Generated by Django 3.2.23 on 2024-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0016_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeimage',
            name='canlike',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='takeimage',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='takeimage',
            name='unlikecount',
            field=models.IntegerField(default=0),
        ),
    ]
