# Generated by Django 3.2.23 on 2024-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0017_auto_20241002_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nickname',
            field=models.TextField(null=True),
        ),
    ]
