# Generated by Django 3.2.23 on 2024-12-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0018_order_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='telephone',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
